import type { Customer } from "./types"

export const mockCustomers: Customer[] = [
  {
    id: "1",
    name: "Rahul Sharma",
    phone: "+91 9876543210",
    email: "rahul@example.com",
    address: "123 Main Street, Mumbai",
    outstandingBalance: 5000,
    nextDueDate: "2023-06-15",
    status: "overdue",
    transactions: [
      {
        id: "t1",
        customerId: "1",
        date: "2023-05-01",
        itemName: "Rice (25kg)",
        amount: 3000,
        dueDate: "2023-06-01",
        status: "partially-paid",
        remainingBalance: 2000,
        repayments: [
          {
            id: "r1",
            transactionId: "t1",
            date: "2023-05-15",
            amount: 1000,
          },
        ],
      },
      {
        id: "t2",
        customerId: "1",
        date: "2023-05-10",
        itemName: "Flour (10kg)",
        amount: 1500,
        dueDate: "2023-06-10",
        status: "unpaid",
        remainingBalance: 1500,
        repayments: [],
      },
      {
        id: "t3",
        customerId: "1",
        date: "2023-05-20",
        itemName: "Sugar (5kg)",
        amount: 1500,
        dueDate: "2023-06-20",
        status: "unpaid",
        remainingBalance: 1500,
        repayments: [],
      },
    ],
  },
  {
    id: "2",
    name: "Priya Patel",
    phone: "+91 9876543211",
    email: "priya@example.com",
    address: "456 Park Avenue, Delhi",
    outstandingBalance: 2500,
    nextDueDate: "2023-06-20",
    status: "up-to-date",
    transactions: [
      {
        id: "t4",
        customerId: "2",
        date: "2023-05-05",
        itemName: "Cooking Oil (5L)",
        amount: 1500,
        dueDate: "2023-06-05",
        status: "partially-paid",
        remainingBalance: 500,
        repayments: [
          {
            id: "r2",
            transactionId: "t4",
            date: "2023-05-20",
            amount: 1000,
          },
        ],
      },
      {
        id: "t5",
        customerId: "2",
        date: "2023-05-15",
        itemName: "Tea (1kg)",
        amount: 2000,
        dueDate: "2023-06-15",
        status: "unpaid",
        remainingBalance: 2000,
        repayments: [],
      },
    ],
  },
  {
    id: "3",
    name: "Amit Kumar",
    phone: "+91 9876543212",
    email: "amit@example.com",
    address: "789 Lake View, Bangalore",
    outstandingBalance: 7500,
    nextDueDate: "2023-06-10",
    status: "overdue",
    transactions: [
      {
        id: "t6",
        customerId: "3",
        date: "2023-04-15",
        itemName: "Wheat (50kg)",
        amount: 5000,
        dueDate: "2023-05-15",
        status: "partially-paid",
        remainingBalance: 3000,
        repayments: [
          {
            id: "r3",
            transactionId: "t6",
            date: "2023-05-01",
            amount: 2000,
          },
        ],
      },
      {
        id: "t7",
        customerId: "3",
        date: "2023-05-01",
        itemName: "Pulses (10kg)",
        amount: 3000,
        dueDate: "2023-06-01",
        status: "partially-paid",
        remainingBalance: 2000,
        repayments: [
          {
            id: "r4",
            transactionId: "t7",
            date: "2023-05-15",
            amount: 1000,
          },
        ],
      },
      {
        id: "t8",
        customerId: "3",
        date: "2023-05-10",
        itemName: "Spices",
        amount: 2500,
        dueDate: "2023-06-10",
        status: "unpaid",
        remainingBalance: 2500,
        repayments: [],
      },
    ],
  },
  {
    id: "4",
    name: "Sunita Verma",
    phone: "+91 9876543213",
    email: "sunita@example.com",
    address: "101 Green Park, Chennai",
    outstandingBalance: 0,
    nextDueDate: "-",
    status: "up-to-date",
    transactions: [
      {
        id: "t9",
        customerId: "4",
        date: "2023-04-20",
        itemName: "Rice (10kg)",
        amount: 1200,
        dueDate: "2023-05-20",
        status: "paid",
        remainingBalance: 0,
        repayments: [
          {
            id: "r5",
            transactionId: "t9",
            date: "2023-05-10",
            amount: 1200,
          },
        ],
      },
    ],
  },
  {
    id: "5",
    name: "Vikram Singh",
    phone: "+91 9876543214",
    email: "vikram@example.com",
    address: "222 River Road, Kolkata",
    outstandingBalance: 4000,
    nextDueDate: "2023-06-25",
    status: "up-to-date",
    transactions: [
      {
        id: "t10",
        customerId: "5",
        date: "2023-05-25",
        itemName: "Grocery Package",
        amount: 4000,
        dueDate: "2023-06-25",
        status: "unpaid",
        remainingBalance: 4000,
        repayments: [],
      },
    ],
  },
]
